# Generated by Django 5.1.15 on 2026-02-07 03:32

from django.db import migrations


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('users', 'UserProfile')

    # Group name → role mapping
    group_role_map = {
        'A-Team': 'admin',
        'VP': 'senior_leadership',
        'Manager': 'department_owner',
        'Owner': 'department_owner',
    }

    for user in User.objects.all():
        if not UserProfile.objects.filter(user=user).exists():
            # Determine role from existing group membership
            role = 'staff'
            groups = user.groups.values_list('name', flat=True)
            for group_name, mapped_role in group_role_map.items():
                if group_name in groups:
                    role = mapped_role
                    break
            UserProfile.objects.create(user=user, role=role)


def reverse_func(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profiles_for_existing_users, reverse_func),
    ]
