# Generated by Django 5.1.15 on 2026-02-07 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0004_vertical_general_manager'),
        ('users', '0002_seed_user_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_unit.businessunit'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('senior_leadership', 'Senior Leadership'), ('supervisor', 'Supervisor'), ('general_manager', 'General Manager'), ('staff', 'Staff')], default='staff', max_length=30),
        ),
    ]
