# Generated by Django 5.1.15 on 2026-09-11 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0013_rename_vertical_businessunit_department'),
        ('users', '0003_userprofile_department_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_unit.department'),
        ),
    ]
