# Generated by Django 5.1.15 on 2026-09-14 21:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('executive', 'Executive'), ('business_unit_leader', 'Business Unit Leader'), ('business_unit_user', 'Business Unit User'), ('analyst', 'Analyst'), ('developer', 'Developer')], max_length=200),
        ),
    ]
