# Generated by Django 5.1.15 on 2026-09-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_lander',
            field=models.CharField(blank=True, choices=[('', 'Use my role default'), ('pipeline', 'Project Value Pipeline'), ('kanban', 'Kanban'), ('grow_sales', 'Grow Sales (Analytics)'), ('storyboard', 'Performance Storyboard')], default='', max_length=20),
        ),
    ]
