# Generated by Django 5.1.15 on 2026-09-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_default_lander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_lander',
            field=models.CharField(blank=True, choices=[('', 'Use my role default'), ('pipeline', 'Project Pipeline Value'), ('kanban', 'Kanban'), ('grow_sales', 'Grow Sales (Analytics)'), ('storyboard', 'Performance Storyboard')], default='', max_length=20),
        ),
    ]
