# Generated by Django 5.1.15 on 2026-06-25 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_unit', '0005_add_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic_goal', models.IntegerField(blank=True, default=35000000, null=True)),
                ('ips_goal', models.IntegerField(blank=True, default=550, null=True)),
                ('ipf_goal', models.FloatField(blank=True, default=1.5, null=True)),
                ('combined_revenue_goal', models.IntegerField(blank=True, default=350000000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Annual Goals',
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.kpi')),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=75, null=True)),
                ('impact', models.CharField(max_length=75, null=True)),
                ('goal', models.CharField(max_length=75, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], null=True)),
                ('level', models.CharField(choices=[('Corporate', 'Corporate'), ('Department', 'Department'), ('Team', 'Team')], default='Corporate', max_length=75, null=True)),
                ('competitive_position', models.IntegerField(blank=True, choices=[(63, 'Niche Player - Low Vision/Low Execution'), (94, 'Niche Player - Low Vision/High Execution'), (94, 'Niche Player - High Vision/Low Execution'), (125, 'Niche Player - High Vision/High Execution'), (150, 'Visionary - Low Vision/Low Execution'), (188, 'Visionary - Low Vision/High Execution'), (188, 'Visionary - High Vision/Low Execution'), (225, 'Visionary - High Vision/High Execution'), (175, 'Challenger - Low Vision/Low Execution'), (219, 'Challenger - Low Vision/High Execution'), (219, 'Challenger - High Vision/Low Execution'), (263, 'Challenger - High Vision/High Execution'), (300, 'Leader - Low Vision/Low Execution'), (350, 'Leader - Low Vision/High Execution'), (350, 'Leader - High Vision/Low Execution'), (400, 'Leader - High Vision/High Execution')], default=63, null=True)),
                ('purpose', models.CharField(choices=[('New Growth', 'New Growth'), ('Hold Position', 'Hold Position'), ('Defend Position', 'Defend Position'), ('Reverse Decay', 'Reverse Decay')], default='New Growth', max_length=75, null=True)),
                ('why', models.TextField(max_length=400)),
                ('definition_of_done', models.CharField(blank=True, max_length=350)),
                ('target_completion', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_unit.businessunit')),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.metric')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='strategy.objective')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='strategy.project')),
            ],
        ),
    ]
