# Generated by Django 5.1.15 on 2026-02-06 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=75, null=True)),
                ('impact', models.CharField(max_length=75, null=True)),
                ('goal', models.CharField(max_length=75, null=True)),
                ('objective', models.CharField(choices=[('IC', 'Increase Shopper Volume'), ('IPS', 'Increase Shopping Activity'), ('IPF', 'Increase Average Order Value')], default='IC', max_length=75, null=True)),
                ('level', models.CharField(choices=[('Corporate', 'Corporate'), ('Business Unit', 'Business Unit'), ('Team', 'Team')], default='Corporate', max_length=75, null=True)),
                ('business_unit', models.CharField(blank=True, choices=[('Merchandising', 'Merchandising'), ('Customer Service', 'Customer Service'), ('Innovation', 'Innovation')], max_length=75, null=True)),
                ('competitive_position', models.IntegerField(blank=True, choices=[(63, 'Niche Player - Low Vision/Low Execution'), (94, 'Niche Player - Low Vision/High Execution'), (94, 'Niche Player - High Vision/Low Execution'), (125, 'Niche Player - High Vision/High Execution'), (150, 'Visionary - Low Vision/Low Execution'), (188, 'Visionary - Low Vision/High Execution'), (188, 'Visionary - High Vision/Low Execution'), (225, 'Visionary - High Vision/High Execution'), (175, 'Challenger - Low Vision/Low Execution'), (219, 'Challenger - Low Vision/High Execution'), (219, 'Challenger - High Vision/Low Execution'), (263, 'Challenger - High Vision/High Execution'), (300, 'Leader - Low Vision/Low Execution'), (350, 'Leader - Low Vision/High Execution'), (350, 'Leader - High Vision/Low Execution'), (400, 'Leader - High Vision/High Execution')], default=63, null=True)),
                ('purpose', models.CharField(choices=[('New Growth', 'New Growth'), ('Hold Position', 'Hold Position'), ('Defend Position', 'Defend Position'), ('Reverse Decay', 'Reverse Decay')], default='New Growth', max_length=75, null=True)),
                ('why', models.TextField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Strategies',
            },
        ),
        migrations.CreateModel(
            name='StrategyGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic_goal', models.IntegerField(blank=True, default=35000000, null=True)),
                ('ips_goal', models.IntegerField(blank=True, default=550, null=True)),
                ('ipf_goal', models.FloatField(blank=True, default=1.5, null=True)),
                ('combined_revenue_goal', models.IntegerField(blank=True, default=350000000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Strategy Goals',
            },
        ),
        migrations.CreateModel(
            name='StrategyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='strategy.strategy')),
            ],
        ),
    ]
