# Generated by Django 5.1.15 on 2026-02-06 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0003_vertical_alter_businessunit_options_and_more'),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Annual Rock',
                'verbose_name_plural': 'Annual Rocks',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': 'Quarterly Rock', 'verbose_name_plural': 'Quarterly Rocks'},
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='objective',
        ),
        migrations.AddField(
            model_name='strategy',
            name='definition_of_done',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='strategy',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_unit.businessunit'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='quarter',
            field=models.IntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='target_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='level',
            field=models.CharField(choices=[('Corporate', 'Corporate'), ('Department', 'Department'), ('Team', 'Team')], default='Corporate', max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='annual_rock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.annualrock'),
        ),
    ]
