# Generated by Django 5.1.15 on 2026-02-06 23:20

from django.db import migrations


def seed_data(apps, schema_editor):
    AnnualRock = apps.get_model('strategy', 'AnnualRock')
    Metric = apps.get_model('strategy', 'Metric')
    KPI = apps.get_model('strategy', 'KPI')

    # Seed Annual Rocks
    for name in [
        'Increase Shopper Volume',
        'Increase Shopping Activity',
        'Increase Average Order Value',
    ]:
        AnnualRock.objects.get_or_create(name=name)

    # Seed Metrics
    for name in ['Users', 'Product Views', 'Add to Carts', 'Begin Checkouts']:
        Metric.objects.get_or_create(name=name, defaults={'active': True})

    # Seed KPIs
    for name in ['MTS', 'Average Order Value', 'Conversion Rate']:
        KPI.objects.get_or_create(name=name, defaults={'active': True})


def reverse_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_annualrock_kpi_metric_alter_strategy_options_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed),
    ]
