# Generated by Django 5.1.15 on 2026-09-15 22:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0015_ga4dailyrollup'),
        ('strategy', '0003_alter_project_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='aee_alignment',
            field=models.CharField(blank=True, choices=[('', '---------'), ('attract_traffic', 'Attract Traffic'), ('engage_customers', 'Engage Customers'), ('expand_purchase', 'Expand Purchase')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='business_risk',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='project',
            name='business_value',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_savings',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_value',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='project',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='level_of_effort',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='project',
            name='normalized_score',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='operational_cost',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Incomplete Entry', 'Incomplete Entry'), ('Ready to Score', 'Ready to Score'), ('Scored', 'Scored'), ('Executive Approval', 'Executive Approval'), ('On Deck', 'On Deck'), ('WIP', 'WIP'), ('Blocked', 'Blocked'), ('Complete', 'Complete'), ('Launched', 'Launched')], default=None, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='business_unit.businessunit'),
        ),
    ]
