# Generated by Django 5.1.15 on 2026-09-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_promote_actions_to_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='effort_size',
            field=models.CharField(blank=True, choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='', max_length=4),
        ),
    ]
