# Generated by Django 5.1.15 on 2026-09-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_project_effort_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='algo_raw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='capability',
            field=models.CharField(blank=True, choices=[('', '---------'), ('fully', 'Fully capable in-house'), ('mostly', 'Mostly capable'), ('stretch', 'Partially / stretch'), ('new', 'Needs new capability'), ('unable', 'Not currently capable')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='project',
            name='direct_expense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='lever',
            field=models.CharField(blank=True, choices=[('', '---------'), ('visitors', 'Visitors'), ('visits_per_visitor', 'Visits per Visitor'), ('cart_creation', 'Cart Creation Rate'), ('cart_completion', 'Cart Completion Rate'), ('units_per_order', 'Units per Order'), ('avg_unit_price', 'Avg Unit Price')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='plausibility_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='project',
            name='ramp_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='project',
            name='s0_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_from',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_to',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='voted_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
