# Generated by Django 5.1.15 on 2026-09-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0007_project_algo_raw_project_capability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='evidence_backed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='evidence_kind',
            field=models.CharField(blank=True, choices=[('prior_level', 'Restoring a prior sustained level'), ('ab_test', 'A/B or experiment result'), ('benchmark', 'External / competitor benchmark'), ('other', 'Other (see note)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='evidence_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='evidence_prior_level',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
    ]
