# Generated by Django 5.1.15 on 2026-02-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Merchandising', 'Merchandising'), ('Customer Service', 'Customer Service'), ('Innovation', 'Innovation'), ('Marketing', 'Marketing')], max_length=140)),
            ],
            options={
                'verbose_name_plural': 'Business Units',
            },
        ),
    ]
