# Generated by Django 5.1.15 on 2026-02-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0002_businessunit_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name': 'Vertical',
                'verbose_name_plural': 'Verticals',
            },
        ),
        migrations.AlterModelOptions(
            name='businessunit',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
