# Generated by Django 5.1.15 on 2026-05-07 22:04

from django.db import migrations, models


DEFAULT_TEAMS = [
    'Marketing',
    'IT',
    'Merchandising',
    'UI/UX',
    'Analytics',
    'Operations',
    'Content',
    'Customer Service',
]


def seed_teams(apps, schema_editor):
    Team = apps.get_model('business_unit', 'Team')
    for name in DEFAULT_TEAMS:
        Team.objects.get_or_create(name=name)


def unseed_teams(apps, schema_editor):
    Team = apps.get_model('business_unit', 'Team')
    Team.objects.filter(name__in=DEFAULT_TEAMS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0004_vertical_general_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_teams, unseed_teams),
    ]
