# Generated by Django 5.1.15 on 2026-09-06 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0006_company_googleidentity_property_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='property',
        ),
        migrations.AddField(
            model_name='vertical',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verticals', to='business_unit.company'),
        ),
        migrations.AddField(
            model_name='vertical',
            name='currency',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='vertical',
            name='ga4_property_id',
            field=models.CharField(blank=True, help_text='Numeric GA4 property id', max_length=50),
        ),
        migrations.AddField(
            model_name='vertical',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='website',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='business_unit.vertical'),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
