# Generated by Django 5.1.15 on 2026-09-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0007_remove_website_property_vertical_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ga4_account_id',
            field=models.CharField(blank=True, help_text='GA4 account id this company was imported from', max_length=50),
        ),
    ]
