# Generated by Django 5.1.15 on 2026-09-08 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0008_company_ga4_account_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BigQueryConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcp_project', models.CharField(blank=True, max_length=100)),
                ('service_account_json', models.JSONField(blank=True, default=dict)),
                ('cart_page_path', models.CharField(blank=True, max_length=255)),
                ('checkout_page_path', models.CharField(blank=True, max_length=255)),
                ('billing_shipping_page_path', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bigquery', to='business_unit.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BigQuery connection',
            },
        ),
    ]
