# Generated by Django 5.1.15 on 2026-09-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0009_bigqueryconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigqueryconnection',
            name='billing_shipping_page_path',
        ),
        migrations.RemoveField(
            model_name='bigqueryconnection',
            name='cart_page_path',
        ),
        migrations.RemoveField(
            model_name='bigqueryconnection',
            name='checkout_page_path',
        ),
        migrations.AddField(
            model_name='bigqueryconnection',
            name='data_through',
            field=models.DateField(blank=True, null=True),
        ),
    ]
