# Generated by Django 5.1.15 on 2026-09-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0010_remove_bigqueryconnection_billing_shipping_page_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigqueryconnection',
            name='event_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
