# Generated by Django 5.1.15 on 2026-09-11 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0011_bigqueryconnection_event_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('agency', 'Agency'), ('direct', 'Direct')], default='direct', max_length=20)),
                ('is_platform_demo', models.BooleanField(default=False, help_text='Demo org shown to all trial orgs')),
                ('trial_started', models.DateField(blank=True, help_text='Trial clock start; null once on a paid plan or internal', null=True)),
                ('plan_status', models.CharField(default='trial', help_text='trial | active | past_due (billing wired later)', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('org_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_orgs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='business_unit.organization'),
        ),
    ]
