# Generated by Django 5.1.15 on 2026-09-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0013_rename_vertical_businessunit_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymembership',
            name='allowed_bus',
            field=models.ManyToManyField(blank=True, related_name='scoped_memberships', to='business_unit.businessunit'),
        ),
    ]
