# Generated by Django 5.1.15 on 2026-09-12 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0014_companymembership_allowed_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='GA4DailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('visits', models.FloatField(default=0)),
                ('visitors', models.FloatField(default=0)),
                ('new_visitors', models.FloatField(default=0)),
                ('carts', models.FloatField(default=0)),
                ('orders', models.FloatField(default=0)),
                ('units', models.FloatField(default=0)),
                ('sales', models.FloatField(default=0)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('device', models.JSONField(blank=True, default=dict)),
                ('channel', models.JSONField(blank=True, default=dict)),
                ('categories', models.JSONField(blank=True, default=dict)),
                ('item_orders', models.FloatField(default=0)),
                ('unique_skus_weighted', models.FloatField(default=0)),
                ('single_sku_orders', models.FloatField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_rollups', to='business_unit.company')),
            ],
            options={
                'verbose_name': 'GA4 daily rollup',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['company', 'property_id', 'date'], name='business_un_company_c5066b_idx')],
                'unique_together': {('company', 'property_id', 'date')},
            },
        ),
    ]
