# Generated by Django 5.1.15 on 2026-09-24 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0015_ga4dailyrollup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise'), ('addon', 'Add-on')], default='standard', max_length=20)),
                ('tagline', models.CharField(blank=True, help_text='The question this plan answers for the buyer', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price in USD for the interval below', max_digits=8)),
                ('interval', models.CharField(default='month', help_text='Billing interval (month / year)', max_length=10)),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('is_addon', models.BooleanField(default=False, help_text='Purchasable alongside a base plan (e.g. Premium Connection)')),
                ('highlighted', models.BooleanField(default=False, help_text='Visually feature this plan as "most popular"')),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('stripe_product_id', models.CharField(blank=True, max_length=80)),
                ('stripe_price_id', models.CharField(blank=True, max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='premium_connection',
            field=models.BooleanField(default=False, help_text='Standard add-on: warehouse-grade BigQuery connection'),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='business_unit.plan'),
        ),
    ]
