# Generated by Django 5.1.15 on 2026-09-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0016_plan_organization_premium_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='address2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='postal',
            field=models.CharField(blank=True, max_length=40, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='company',
            name='same_as_billing',
            field=models.BooleanField(default=False, help_text='Reuse the organization billing address for this company'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=120, verbose_name='State / Region'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_address1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Billing address'),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_address2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Billing address line 2'),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_postal',
            field=models.CharField(blank=True, max_length=40, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_state',
            field=models.CharField(blank=True, max_length=120, verbose_name='State / Region'),
        ),
        migrations.AddField(
            model_name='organization',
            name='canceled_at',
            field=models.DateTimeField(blank=True, help_text='Account canceled by the org admin', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='Admin paused this account', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='purge_after',
            field=models.DateField(blank=True, help_text='Canceled data is deleted forever on/after this date (canceled_at + 90 days)', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan_status',
            field=models.CharField(default='trial', help_text='trial | active | past_due | paused | canceled', max_length=20),
        ),
    ]
