# Generated by Django 5.1.15 on 2026-02-06 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('totalAdSpend', models.CharField(max_length=75)),
                ('roas', models.CharField(max_length=75)),
                ('users', models.CharField(max_length=75)),
                ('newUsers', models.CharField(max_length=75)),
                ('sessions', models.CharField(max_length=75)),
                ('sessionsPerUser', models.CharField(max_length=75)),
                ('pageviews', models.CharField(max_length=75)),
                ('revenue', models.CharField(max_length=75)),
                ('avgOrderValue', models.CharField(max_length=75)),
                ('transactions', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='DailyActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(blank=True)),
                ('date_modified', models.DateField(blank=True)),
                ('name', models.CharField(blank=True, max_length=75)),
                ('desired_impact', models.CharField(blank=True, max_length=75)),
                ('def_of_success', models.CharField(blank=True, max_length=75)),
                ('iep_alignment', models.CharField(blank=True, choices=[('impress', 'Impress'), ('enlighten', 'Enlighten'), ('purchase', 'Purchase')], max_length=75)),
                ('feature_locations', models.CharField(blank=True, choices=[('header', 'Header'), ('footer', 'Footer'), ('home_page', 'Home Page'), ('category_page', 'Category Page'), ('product_list_page', 'Product List Page'), ('product_detail_page', 'Product Detail Page'), ('cart_part', 'Cart Page'), ('order_tracking_page', 'Order Tracking Page'), ('landing_page', 'Landing Page')], max_length=75)),
                ('engagement', models.CharField(blank=True, choices=[('click', 'Click'), ('submit', 'Submit'), ('view', 'View')], max_length=75)),
                ('competitive_position', models.IntegerField(blank=True)),
                ('purpose', models.CharField(blank=True, choices=[('new_growth', 'New Growth'), ('hold_position', 'Hold Position'), ('defend_position', 'Defend Position'), ('reverse_decay', 'Reverse Decay')], max_length=75)),
                ('why', models.CharField(blank=True, max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('date_created', models.DateField(null=True)),
                ('date_modified', models.DateField(null=True)),
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, null=True)),
                ('desired_impact', models.CharField(max_length=75, null=True)),
                ('def_of_success', models.CharField(max_length=75, null=True)),
                ('next_launch', models.DateField(null=True)),
                ('alignment', models.CharField(choices=[('increase_customers', 'Increase Customers'), ('increase_aov', 'Increase AOV'), ('increase_purchase_frequency', 'Increase Purchase Frequency')], max_length=75, null=True)),
                ('level', models.CharField(choices=[('corporate', 'Corporate'), ('business_unit', 'Business Unit'), ('team', 'Team')], max_length=75, null=True)),
                ('purpose', models.CharField(choices=[('new_growth', 'New Growth'), ('hold_position', 'Hold Position'), ('defend_position', 'Defend Position'), ('reverse_decay', 'Reverse Decay')], max_length=75, null=True)),
                ('score', models.IntegerField(null=True)),
                ('value', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('gathering_requirements', 'Gathering Requirements'), ('ready_for_dev', 'Ready for Development'), ('in_development', 'In Development'), ('uat', 'UAT'), ('qa', 'QA'), ('ready_for_prod', 'Ready for Production'), ('completed_launched', 'Completed - Launched'), ('blocked', 'Blocked')], max_length=75, null=True)),
                ('progress', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('date_modified', models.DateField()),
                ('name', models.CharField(max_length=75)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='strategy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.strategy'),
        ),
    ]
