# Generated by Django 5.1.15 on 2026-02-07 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('business_unit', '0004_vertical_general_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactual',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_unit.vertical'),
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_unit.vertical'),
        ),
        migrations.AlterField(
            model_name='dailyactual',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='dailyactual',
            unique_together={('date', 'vertical')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlygoal',
            unique_together={('month', 'vertical')},
        ),
    ]
