# Generated by Django 5.1.15 on 2026-05-08 01:56

import random
from decimal import Decimal
from django.db import migrations, models


# Per-year AOV/close-rate targets for backfill — tuned to show YoY uplift in 2026
YEAR_PROFILES = {
    2024: {'aov_mean': 440, 'aov_jitter': 35, 'close_rate_mean': 0.0140, 'close_rate_jitter': 0.0025},
    2025: {'aov_mean': 460, 'aov_jitter': 35, 'close_rate_mean': 0.0148, 'close_rate_jitter': 0.0025},
    2026: {'aov_mean': 478, 'aov_jitter': 35, 'close_rate_mean': 0.0156, 'close_rate_jitter': 0.0025},
}
DEFAULT_PROFILE = {'aov_mean': 470, 'aov_jitter': 35, 'close_rate_mean': 0.0150, 'close_rate_jitter': 0.0025}


def backfill_visits_orders(apps, schema_editor):
    DailyActual = apps.get_model('app', 'DailyActual')
    rng = random.Random(7)
    updates = []
    for row in DailyActual.objects.all().iterator():
        profile = YEAR_PROFILES.get(row.date.year, DEFAULT_PROFILE)
        aov = max(50.0, rng.gauss(profile['aov_mean'], profile['aov_jitter']))
        close_rate = max(0.002, rng.gauss(profile['close_rate_mean'], profile['close_rate_jitter']))
        revenue = float(row.revenue or 0)
        orders = max(0, int(round(revenue / aov))) if revenue > 0 else 0
        visits = max(orders, int(round(orders / close_rate))) if orders > 0 else 0
        row.orders = orders
        row.visits = visits
        updates.append(row)
        if len(updates) >= 500:
            DailyActual.objects.bulk_update(updates, ['orders', 'visits'])
            updates = []
    if updates:
        DailyActual.objects.bulk_update(updates, ['orders', 'visits'])


def reverse_backfill(apps, schema_editor):
    DailyActual = apps.get_model('app', 'DailyActual')
    DailyActual.objects.update(orders=0, visits=0)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dailyactual_vertical_monthlygoal_vertical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactual',
            name='orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyactual',
            name='visits',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_visits_orders, reverse_backfill),
    ]
