# Generated by Django 5.1.15 on 2026-09-11 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_purchase_frequency_alignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessUnit',
        ),
    ]
