# Generated by Django 5.1.15 on 2026-09-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_businessunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('sales', 'Sales'), ('visits', 'Visits'), ('visitors', 'Visitors'), ('orders', 'Orders'), ('close_rate', 'Close Rate'), ('aov', 'Average Order Value'), ('cart_creation', 'Cart Creation Rate'), ('cart_completion', 'Cart Completion Rate'), ('units_per_order', 'Units per Order'), ('avg_unit_price', 'Average Unit Price')], max_length=40)),
                ('direction', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss')], help_text='win = amplify the gain; loss = mitigate the decline', max_length=4)),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (A, B, C, ...)')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Metric recommendation',
                'ordering': ['metric', 'direction', 'order', 'id'],
            },
        ),
    ]
