# Generated by Django 5.1.15 on 2026-09-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_metricrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendGridSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='SendGrid API key (leave blank until provisioned)', max_length=255)),
                ('from_email', models.EmailField(default='no-reply@kibokomethod.com', help_text='Verified SendGrid sender address', max_length=254)),
                ('from_name', models.CharField(blank=True, default='Kiboko', max_length=120)),
                ('feedback_to', models.EmailField(default='feedback@kibokomethod.com', help_text='Where user feedback is delivered', max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SendGrid settings',
                'verbose_name_plural': 'SendGrid settings',
            },
        ),
    ]
