"""
Django settings for gentelella project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cdby6+6l6tg7+$vhoh1wfh!qi*d1()t=gz7@-dpqq_nd5ihk#_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tables2',
    'app',
    'strategy',
    'project',
    'users',
    'business_unit',
    'multiselectfield',
    'crispy_forms',
    'crispy_bootstrap3',
    'django.contrib.humanize',
    'computedfields',
    'widget_tweaks',
]

COMPUTEDFIELDS_ADMIN = True

CRISPY_TEMPLATE_PACK = 'bootstrap3'
CRISPY_ALLOWED_TEMPLATE_PACKS = ('bootstrap3',)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.ForcePasswordChangeMiddleware',
]

ROOT_URLCONF = 'gentelella.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.tenancy_selector',
                'app.context_processors.google_flags',
                'app.context_processors.getting_started_banner',
                'app.context_processors.plan_features',
            ],
        },
    },
]

WSGI_APPLICATION = 'gentelella.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        # SQLite is single-writer: a long write (e.g. the demo seed) can lock the
        # file while web workers read/write the session table. Wait up to 30s for
        # a lock instead of erroring at the 5s default — this prevents the
        # "database is locked" 500s during a deploy/seed. (WAL is intentionally
        # NOT enabled: it's unreliable on PythonAnywhere's networked filesystem.)
        'OPTIONS': {'timeout': 30},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static'
LOGIN_URL = '/users/login/'
# Post-login dispatcher picks the landing page by role (or the user's override).
LOGIN_REDIRECT_URL = '/app/home/'

# --- Google OAuth / GA4 Data API -----------------------------------------
# Real credentials live in gitignored local_settings.py. When the client id +
# secret are set, "Sign in with Google" + live GA4 activate; until then the app
# falls back to the existing login (see app.integrations.google_oauth.is_enabled).
GOOGLE_OAUTH_CLIENT_ID = ''
GOOGLE_OAUTH_CLIENT_SECRET = ''
GOOGLE_OAUTH_REDIRECT_URI = 'http://localhost:8000/auth/google/callback/'

# Premium (BigQuery) reads prefer the GA4DailyRollup cache when it covers the
# requested range; otherwise they fall back to a live BigQuery scan. Set False to
# always read live (e.g. while validating the sync).
GA4_USE_ROLLUP = True
GOOGLE_OAUTH_SCOPES = [
    'openid',
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
    # analytics.readonly covers BOTH the Admin API (list accounts/properties/
    # streams) and the Data API (run reports).
    'https://www.googleapis.com/auth/analytics.readonly',
]

# --- Per-environment overrides -------------------------------------------
# Keep this committed settings.py at dev defaults. Put server-specific values
# (DEBUG=False, SECRET_KEY, ALLOWED_HOSTS, DATABASES, etc.) in a gitignored
# gentelella/local_settings.py so `git pull` never conflicts with the server
# config. Anything defined there overrides the values above.
try:
    from .local_settings import *  # noqa: F401,F403
except ImportError:
    pass
