# Generated by Django 5.1.15 on 2026-02-06 18:26

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_unit', '0002_businessunit_owner'),
        ('strategy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=350)),
                ('impact', models.CharField(blank=True, max_length=350, verbose_name='Definition of Done')),
                ('success', models.CharField(blank=True, max_length=350)),
                ('alignment', models.CharField(choices=[('Impress', 'Impress'), ('Enlighten', 'Enlighten'), ('Purchase', 'Purchase')], default='Impress', max_length=350, null=True)),
                ('locations', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Header', 'Header'), ('Footer', 'Footer'), ('Home Page', 'Home Page'), ('Category Page', 'Category Page'), ('Product List Page', 'Product List Page'), ('Product Detail Page', 'Product Detail Page'), ('Cart Page', 'Cart Page'), ('Order Tracking Page', 'Order Tracking Page'), ('Landing Page', 'Landing Page')], max_length=300)),
                ('engagement', models.CharField(choices=[('Click', 'Click'), ('Submit', 'Submit'), ('View', 'View')], default='Click', max_length=350, null=True)),
                ('competitive_position', models.IntegerField(blank=True, choices=[(63, 'Niche Player - Low Vision/Low Execution'), (94, 'Niche Player - Low Vision/High Execution'), (94, 'Niche Player - High Vision/Low Execution'), (125, 'Niche Player - High Vision/High Execution'), (150, 'Visionary - Low Vision/Low Execution'), (188, 'Visionary - Low Vision/High Execution'), (188, 'Visionary - High Vision/Low Execution'), (225, 'Visionary - High Vision/High Execution'), (175, 'Challenger - Low Vision/Low Execution'), (219, 'Challenger - Low Vision/High Execution'), (219, 'Challenger - High Vision/Low Execution'), (263, 'Challenger - High Vision/High Execution'), (300, 'Leader - Low Vision/Low Execution'), (350, 'Leader - Low Vision/High Execution'), (350, 'Leader - High Vision/Low Execution'), (400, 'Leader - High Vision/High Execution')], default=63, null=True)),
                ('purpose', models.CharField(choices=[('New Growth', 'New Growth'), ('Hold Position', 'Hold Position'), ('Defend Position', 'Defend Position'), ('Reverse Decay', 'Reverse Decay')], default='New Growth', max_length=350, null=True)),
                ('why', models.TextField(blank=True, max_length=500, verbose_name='User Story')),
                ('loe', models.CharField(blank=True, choices=[('NA', 'NA'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='NA', max_length=350, null=True)),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('progress', models.IntegerField(blank=True, default=0, null=True)),
                ('scored', models.BooleanField(blank=True, editable=False, null=True)),
                ('valued', models.BooleanField(blank=True, editable=False, null=True)),
                ('launch', models.DateField(blank=True, null=True)),
                ('score', models.IntegerField(default=0, editable=False, null=True)),
                ('normalized_score', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=4, null=True)),
                ('priority', models.IntegerField(default=0, editable=False, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Pending Assignment', 'Pending Assignment'), ('Active', 'Active'), ('Complete', 'Complete'), ('Launched', 'Launched')], default='Pending Approval', max_length=350, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('viability', models.CharField(choices=[('Strong', 'Strong'), ('Able', 'Able'), ('Attainable', 'Attainable'), ('Steep Climb', 'Steep Climb')], default='Steep Climb', max_length=350, null=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_unit.businessunit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='strategy.strategy')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.project')),
            ],
        ),
    ]
