# Generated by Django 5.1.15 on 2026-06-25 21:30

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_unit', '0005_add_team'),
        ('strategy', '0002_seed_reference_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=350)),
                ('impact', models.CharField(blank=True, max_length=350, verbose_name='Definition of Done')),
                ('success', models.CharField(blank=True, max_length=350)),
                ('locations', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Header', 'Header'), ('Footer', 'Footer'), ('Home Page', 'Home Page'), ('Category Page', 'Category Page'), ('Product List Page', 'Product List Page'), ('Product Detail Page', 'Product Detail Page'), ('Cart Page', 'Cart Page'), ('Order Tracking Page', 'Order Tracking Page'), ('Landing Page', 'Landing Page')], max_length=300)),
                ('why', models.TextField(blank=True, max_length=500, verbose_name='User Story')),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('progress', models.IntegerField(blank=True, default=0, null=True)),
                ('launch', models.DateField(blank=True, null=True)),
                ('active_date', models.DateField(blank=True, editable=False, null=True)),
                ('normalized_score', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=4, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Pending Assignment', 'Pending Assignment'), ('On Deck', 'On Deck'), ('Active', 'Active'), ('Complete', 'Complete'), ('Launched', 'Launched')], default='Pending Approval', max_length=350, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('customer_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('business_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('cost_savings', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('operational_cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('business_risk', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('level_of_effort', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('is_blocked', models.BooleanField(default=False)),
                ('strategy_tag', models.CharField(blank=True, choices=[('', '---------'), ('Expand Selection', 'Expand Selection'), ('Improve Experience', 'Improve Experience'), ('Increase Urgency', 'Increase Urgency'), ('Top of Mind', 'Top of Mind')], default='', max_length=50)),
                ('impact_visits_value', models.IntegerField(blank=True, default=0, null=True)),
                ('impact_close_rate_value', models.IntegerField(blank=True, default=0, null=True)),
                ('impact_aov_value', models.IntegerField(blank=True, default=0, null=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_unit.businessunit')),
                ('measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.measure')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.objective')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='strategy.project')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_unit.team')),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_unit.vertical')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['-normalized_score'],
            },
        ),
        migrations.CreateModel(
            name='ActionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.action')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
