# Generated by Django 5.1.15 on 2026-09-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='aee_alignment',
            field=models.CharField(blank=True, choices=[('', '---------'), ('attract_traffic', 'Attract Traffic'), ('engage_customers', 'Engage Customers'), ('expand_purchase', 'Expand Purchase')], default='', max_length=50),
        ),
    ]
