# Generated by Django 5.1.15 on 2026-02-06 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-normalized_score'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='competitive_position',
        ),
        migrations.RemoveField(
            model_name='project',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='project',
            name='loe',
        ),
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='project',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='project',
            name='score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='scored',
        ),
        migrations.RemoveField(
            model_name='project',
            name='valued',
        ),
        migrations.RemoveField(
            model_name='project',
            name='viability',
        ),
        migrations.AddField(
            model_name='project',
            name='business_risk',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='project',
            name='business_value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_savings',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='project',
            name='level_of_effort',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='project',
            name='operational_cost',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
