# Generated by Django 5.1.15 on 2026-02-06 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0003_vertical_alter_businessunit_options_and_more'),
        ('project', '0002_alter_project_options_remove_project_alignment_and_more'),
        ('strategy', '0002_annualrock_kpi_metric_alter_strategy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='annual_rock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.annualrock'),
        ),
        migrations.AddField(
            model_name='project',
            name='kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.kpi'),
        ),
        migrations.AddField(
            model_name='project',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.metric'),
        ),
        migrations.AddField(
            model_name='project',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_unit.vertical'),
        ),
    ]
