# Generated by Django 5.1.15 on 2026-02-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_annual_rock_project_kpi_project_metric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='impact_aov_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_close_rate_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_visits_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='strategy_tag',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Expand Selection', 'Expand Selection'), ('Improve Experience', 'Improve Experience'), ('Increase Urgency', 'Increase Urgency'), ('Top of Mind', 'Top of Mind')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Pending Assignment', 'Pending Assignment'), ('On Deck', 'On Deck'), ('Active', 'Active'), ('Complete', 'Complete'), ('Launched', 'Launched')], default='Pending Approval', max_length=350, null=True),
        ),
    ]
