# Generated by Django 5.1.15 on 2026-09-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_active_status_to_wip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Pending Assignment', 'Pending Assignment'), ('On Deck', 'On Deck'), ('WIP', 'WIP'), ('Complete', 'Complete'), ('Launched', 'Launched')], default='Pending Approval', max_length=350, null=True),
        ),
    ]
