# Generated by Django 5.1.15 on 2026-05-07 21:16

from django.db import migrations, models


def backfill_active_date(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    Project.objects.filter(status='Active', active_date__isnull=True).update(
        active_date=models.F('date_modified')
    )


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_impact_aov_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_active_date, reverse_backfill),
    ]
