# Generated by Django 5.1.15 on 2026-05-07 22:04

import django.db.models.deletion
from django.db import migrations, models


# Match keywords in project name (lowercased) -> team name
KEYWORD_TEAMS = [
    (['ui', 'ux', 'design', 'page', 'checkout', 'visual', 'wireframe', 'prototype'], 'UI/UX'),
    (['seo', 'ad ', 'ads', 'campaign', 'email', 'marketing', 'social', 'brand', 'promo'], 'Marketing'),
    (['analytic', 'data', 'report', 'dashboard', 'metric', 'tracking', 'attribution'], 'Analytics'),
    (['merchand', 'catalog', 'category', 'product list', 'bundle', 'pricing', 'sku', 'assortment'], 'Merchandising'),
    (['api', 'integration', 'infrastructure', 'platform', 'pipeline', 'migration', 'database', 'devops', 'security'], 'IT'),
    (['content', 'blog', 'copy', 'article', 'editorial'], 'Content'),
    (['support', 'service', 'helpdesk', 'cs ', 'ticket', 'returns'], 'Customer Service'),
    (['fulfillment', 'shipping', 'logistic', 'warehouse', 'inventory', 'operation'], 'Operations'),
]

# Round-robin fallback so unmatched projects spread evenly
FALLBACK_TEAMS = ['Marketing', 'Merchandising', 'UI/UX', 'Analytics', 'IT', 'Operations', 'Content']


def backfill_team(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    Team = apps.get_model('business_unit', 'Team')

    teams_by_name = {t.name: t for t in Team.objects.all()}
    fallback_idx = 0

    for project in Project.objects.filter(team__isnull=True).order_by('id'):
        name_lower = (project.name or '').lower()
        matched = None
        for keywords, team_name in KEYWORD_TEAMS:
            if any(kw in name_lower for kw in keywords):
                matched = teams_by_name.get(team_name)
                if matched:
                    break
        if matched is None:
            team_name = FALLBACK_TEAMS[fallback_idx % len(FALLBACK_TEAMS)]
            fallback_idx += 1
            matched = teams_by_name.get(team_name)
        if matched is not None:
            project.team = matched
            project.save(update_fields=['team'])


def reverse_backfill(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    Project.objects.update(team=None)


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0005_add_team'),
        ('project', '0005_add_active_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_unit.team'),
        ),
        migrations.RunPython(backfill_team, reverse_backfill),
    ]
