# Generated by Django 5.1.15 on 2026-09-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_status_equals_kanban_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Incomplete Entry', 'Incomplete Entry'), ('Ready to Score', 'Ready to Score'), ('Scored', 'Scored'), ('On Deck', 'On Deck'), ('WIP', 'WIP'), ('Blocked', 'Blocked'), ('Complete', 'Complete'), ('Launched', 'Launched')], default='Incomplete Entry', max_length=350, null=True),
        ),
    ]
