# Generated by Django 5.1.15 on 2026-09-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_action_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(blank=True, choices=[('Incomplete Entry', 'Incomplete Entry'), ('Ready to Score', 'Ready to Score'), ('Scored', 'Scored'), ('On Deck', 'On Deck'), ('WIP', 'WIP'), ('Blocked', 'Blocked'), ('Complete', 'Complete'), ('Launched', 'Launched')], default=None, max_length=350, null=True),
        ),
    ]
