# Generated by Django 5.1.15 on 2026-09-11 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0013_rename_vertical_businessunit_department'),
        ('project', '0010_alter_action_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_unit.department'),
        ),
        migrations.AlterField(
            model_name='action',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_unit.businessunit'),
        ),
    ]
