# Generated by Django 5.1.15 on 2026-09-14 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0015_ga4dailyrollup'),
        ('project', '0012_alter_action_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_value', models.PositiveSmallIntegerField(default=25)),
                ('business_value', models.PositiveSmallIntegerField(default=40)),
                ('cost_savings', models.PositiveSmallIntegerField(default=10)),
                ('operational_cost', models.PositiveSmallIntegerField(default=10)),
                ('business_risk', models.PositiveSmallIntegerField(default=5)),
                ('level_of_effort', models.PositiveSmallIntegerField(default=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_weights', to='business_unit.company')),
            ],
            options={
                'verbose_name': 'Scoring Weights',
                'verbose_name_plural': 'Scoring Weights',
            },
        ),
    ]
