# Generated by Django 5.1.15 on 2026-09-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_scorevote_level_of_effort_alter_scorevote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='project.action'),
        ),
    ]
