# Generated by Django 5.1.15 on 2026-09-16 17:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0015_ga4dailyrollup'),
        ('project', '0017_action_depends_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_factor', models.DecimalField(decimal_places=2, default=Decimal('0.35'), help_text='Contribution margin (direct-expense revenue factor)', max_digits=4)),
                ('default_ramp_days', models.PositiveSmallIntegerField(default=30)),
                ('baseline_window_days', models.PositiveSmallIntegerField(default=90)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimator_settings', to='business_unit.company')),
            ],
            options={
                'verbose_name': 'Estimator Settings',
                'verbose_name_plural': 'Estimator Settings',
            },
        ),
    ]
